version: '3.1'

services:

  user-services : 
    build:
      context: ./user-auth-service
      dockerfile: Dockerfile
    environment : 
      - MONGOURI=mongodb://network-microservices:27017
      - PORT=3001
    ports:
      - "3001:3001"


  restaurant-services : 
    build:
      context: ./restaurant-service
      dockerfile: Dockerfile
    environment : 
      - MONGOURI=mongodb://network-microservices:27017
      - PORT=3002
    ports:
      - "3002:3002"

  order-services :
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment : 
      - MONGOURI=mongodb://network-microservices:27017
      - PORT=3003
      - restraunt_service=http://network_microservice-restaurant-services-1:3002/
    ports:
      - "3003:3003"

  mongo:
    image: mongo
    container_name: network-microservices
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./data:/data/db